### ISSUE TITLE
[Question] Is this mod abandoned for 3.9?

### ISSUE THREAD

**Issue by logarbLord** [NNThomasL/SPTarkovWebMinimap#5]
from what ive found there hasnt been an update because of difficulty and i was wondering if this project was still being worked on or not.

**Comment by NNThomasL** [comment]
I wish I could keep this mod updated but like I said in the hub comments, my skills aren't there yet. Networking issues and UI design combined with little outside testing caused a bit of stress. I may revisit the mod in the future but I thought that newer alternatives like "Dynamic Maps" made my mod obsolete.

**Comment by logarbLord** [comment]
Fair enough, i really appreciate your reply. Was hoping to get a web based one so i could run a map mod with the new VR mod's release.

**Comment by logarbLord** [comment]
Closing thread
